TRANSACTION_ID_FIELD = "_xact_id"
OBJECT_DELETE_FIELD = "_object_delete"
CREATED_FIELD = "created"
IS_MERGE_FIELD = "_is_merge"
ID_FIELD = "id"

ALL_ROW_ID_FIELDS = [ID_FIELD, TRANSACTION_ID_FIELD, CREATED_FIELD, IS_MERGE_FIELD, OBJECT_DELETE_FIELD]
