import { defineConfig } from "tsup";
import path from "path";

const srcDir = path.resolve(__dirname, "src");

export default defineConfig([
  {
    entry: ["src/index.ts"],
    format: ["cjs"],
    outDir: "dist",
    external: ["zod"],
    noExternal: ["nunjucks"],
    esbuildOptions(options) {
      options.alias = {
        ...options.alias,
        [path.join(srcDir, "template/_platform-nunjucks")]: path.join(srcDir, "template/_platform-nunjucks-cjs"),
      };
    },
    dts: {
      // Split DTS generation to reduce memory usage
      compilerOptions: {
        skipLibCheck: true,
      },
    },
    splitting: true,
    clean: true,
  },
  {
    entry: ["src/index.ts"],
    format: ["esm"],
    outDir: "dist",
    external: ["zod", "nunjucks"],
    esbuildOptions(options) {
      options.alias = {
        ...options.alias,
        [path.join(srcDir, "template/_platform-nunjucks")]: path.join(srcDir, "template/_platform-nunjucks-esm"),
      };
    },
    dts: false, // DTS already generated by CJS build
    splitting: true,
    clean: false,
  },
  {
    entry: ["src/browser.ts"],
    format: ["cjs"],
    outDir: "dist",
    external: ["nunjucks"],
    noExternal: [],
    esbuildOptions(options) {
      options.alias = {
        ...options.alias,
        [path.join(srcDir, "template/_platform-nunjucks")]: path.join(srcDir, "template/_platform-nunjucks-cjs"),
      };
    },
    dts: {
      // Split DTS generation to reduce memory usage
      compilerOptions: {
        skipLibCheck: true,
      },
    },
    splitting: true,
    clean: false,
  },
  {
    entry: ["src/browser.ts"],
    format: ["esm"],
    outDir: "dist",
    external: ["nunjucks"],
    esbuildOptions(options) {
      options.alias = {
        ...options.alias,
        [path.join(srcDir, "template/_platform-nunjucks")]: path.join(srcDir, "template/_platform-nunjucks-esm"),
      };
    },
    dts: false, // DTS already generated by CJS build
    splitting: true,
    clean: false,
  },
  {
    entry: ["src/cli.ts"],
    format: ["cjs"],
    outDir: "dist",
    external: ["esbuild", "prettier", "typescript"],
    noExternal: ["nunjucks"],
    esbuildOptions(options) {
      options.alias = {
        ...options.alias,
        [path.join(srcDir, "template/_platform-nunjucks")]: path.join(srcDir, "template/_platform-nunjucks-cjs"),
      };
    },
    // CLI doesn't need DTS
    dts: false,
    clean: false,
  },
  {
    entry: ["dev/index.ts"],
    format: ["cjs"],
    outDir: "dev/dist",
    external: ["esbuild", "prettier", "typescript"],
    noExternal: ["nunjucks"],
    esbuildOptions(options) {
      options.alias = {
        ...options.alias,
        [path.join(srcDir, "template/_platform-nunjucks")]: path.join(srcDir, "template/_platform-nunjucks-cjs"),
      };
    },
    dts: {
      // Split DTS generation to reduce memory usage
      compilerOptions: {
        skipLibCheck: true,
      },
    },
    splitting: true,
    clean: true,
  },
  {
    entry: ["dev/index.ts"],
    format: ["esm"],
    outDir: "dev/dist",
    external: ["esbuild", "prettier", "typescript", "nunjucks"],
    esbuildOptions(options) {
      options.alias = {
        ...options.alias,
        [path.join(srcDir, "template/_platform-nunjucks")]: path.join(srcDir, "template/_platform-nunjucks-esm"),
      };
    },
    dts: false, // DTS already generated by CJS build
    splitting: true,
    clean: false,
  },
  {
    entry: ["util/index.ts"],
    format: ["cjs"],
    outDir: "util/dist",
    external: ["esbuild", "prettier", "typescript"],
    noExternal: ["nunjucks"],
    esbuildOptions(options) {
      options.alias = {
        ...options.alias,
        [path.join(srcDir, "template/_platform-nunjucks")]: path.join(srcDir, "template/_platform-nunjucks-cjs"),
      };
    },
    dts: {
      // Split DTS generation to reduce memory usage
      compilerOptions: {
        skipLibCheck: true,
      },
    },
    splitting: true,
    clean: true,
  },
  {
    entry: ["util/index.ts"],
    format: ["esm"],
    outDir: "util/dist",
    external: ["esbuild", "prettier", "typescript", "nunjucks"],
    esbuildOptions(options) {
      options.alias = {
        ...options.alias,
        [path.join(srcDir, "template/_platform-nunjucks")]: path.join(srcDir, "template/_platform-nunjucks-esm"),
      };
    },
    dts: false, // DTS already generated by CJS build
    splitting: true,
    clean: false,
  },
]);
