#!/bin/bash

set -e

d="$(dirname "$0")"

# Loop over all .ts files in that directory
for file in "$d"/*.ts; do
  echo "---------------------------------------------"
  echo "Executing $file..."
  tsx "$file"
done

echo "They all passed"
