# Mise will automatically read and use .tool-versions files as well as this file.

[env]
# Automatically activate our virtual environment
_.python.venv = { path = "venv", create = true, uv_create_args = ['--seed']}

# See env.example to configure API keys.
_.file = ".env"

[tools]
# SDK is a standalone module - include all required tools
pnpm = "10.26.1"
nodejs = "22.15.0"
python = "3.13.3"
pre-commit = "4.2.0"
ruff = "0.12.7"
uv = "latest"
