# Mise will automatically read and use .tool-versions files as well as this file.

[settings]
experimental = true

[env]
# See env.example to configure API keys.
_.file = ".env"

[tools]
nodejs = "22.15.0"
npm = "11.6.2"
pnpm = "10.26.2"
"npm:@sentry/dotagents" = "1.4.0"

[hooks]
postinstall = "pnpm install && dotagents install"
