packages:
  - js
  - js-browser
  - integrations/*
  - internal/golden
  - js/src/wrappers/*
  - "!js/vendor/**"
  - "!internal/golden/*"

ignoredBuiltDependencies:
  - esbuild
  - msw
  - protobufjs
