packages:
  - "js"
  - "core/js"
  - "integrations/*"
  - "internal/golden"
  - "js/src/wrappers/ai-sdk-4"
  - "js/src/wrappers/ai-sdk-5"
  - "js/src/wrappers/mastra"
  - "js/src/wrappers/claude-agent-sdk"
