[project]
name = "golden"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "braintrust>=0.3.1",
    "google-genai>=1.43.0",
]

[tool.uv.sources]
braintrust = { path = "../../py", editable = true }
