from typing import Dict, List, Optional, Pattern, Union

class RequestContext:
    app_origin: Optional[str]
    token: Optional[str]

StaticOrigin = Union[str, Pattern[str]]

def extract_allowed_origin(origin: Optional[str], allowed_origins: List[StaticOrigin]) -> Optional[str]: ...
def check_origin(headers: Dict[str, str], allowed_origins: List[StaticOrigin]) -> Optional[str]: ...
def authorize_request(headers: Dict[str, str]) -> RequestContext: ...
def check_authorized(context: RequestContext) -> bool: ...
