#
# This workflow is used to publish pre-release versions of the JavaScript SDK to npm.
# It can only be triggered manually via workflow_dispatch.
# Pre-release versions use dist-tags (beta, alpha, next) to avoid marking them as "latest".
#
# This workflow does NOT require updating package.json in the repository.
# The version is created temporarily in CI and published, without committing back to the repo.
#
# Usage:
#   - Go to Actions tab in GitHub
#   - Select "Publish JavaScript SDK (Pre-release)"
#   - Click "Run workflow"
#   - Choose pre-release type (beta/alpha/rc) and enter the version to publish
#
# Users can install pre-releases via:
#   npm install braintrust@beta
#   npm install braintrust@alpha
#   npm install braintrust@next  (for rc)
#

name: Publish JavaScript SDK (Pre-release)

on:
  workflow_dispatch:
    inputs:
      prerelease_type:
        description: "Pre-release type (determines npm dist-tag)"
        required: true
        type: choice
        options:
          - beta
          - alpha
          - rc
      version:
        description: "Version to publish (e.g., 1.2.3-beta.1)"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Publish pre-release
        working-directory: js
        run: |
          ./scripts/publish-prerelease.sh "${{ github.event.inputs.prerelease_type }}" "${{ github.event.inputs.version }}"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: javascript-sdk-prerelease-dist
          path: js/dist/
          retention-days: 5
