name: templates-nunjucks-js

on:
  pull_request:
    paths:
      - "integrations/templates-nunjucks/**"
      - "js/**"
      - ".github/workflows/templates-nunjucks-build-test.yaml"
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build braintrust
        working-directory: js
        run: pnpm run build

      - name: Build @braintrust/templates-nunjucks-js
        working-directory: integrations/templates-nunjucks
        run: pnpm run build

      - name: Run @braintrust/templates-nunjucks-js tests
        working-directory: integrations/templates-nunjucks
        run: pnpm run test
